apiVersion: v1 
kind: Pod 
metadata: 
  name: annotations 
  labels: 
    project: roboshop 
    component: mysql 
    tier: backend 
    environment: dev 
  annotations: 
    description: "This POD is created to demonstrate annotations instructions" 
    jenkins: "https://jenkins.com/build/job/roboshop-catalogue/3"  
sepc: 
  containers: 
    - name: nginx 
      image: nginx     
