apiVersion: v1
kind: Pod
metadata:
  name: envvar-demo
  labels: 
    purpose: demonstrate-envvars
spec:
  containers:
  - name: nginx
    image: nginx
    
    env:
    - name: COURSE
      value: "KUBERNETES"
    - name: TRAINER 
      value: "SIVA KUMAR REDDY"  

