apiVersion: v1
kind: Service
metadata:
  name: headless-svc
  labels:
    purpose: statefulset 
    project: roboshop
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    purpose: statefulset 
    project: roboshop
---
apiVersion: v1
kind: Service
metadata:
  name: normal-svc
  labels:
    purpose: statefulset 
    project: roboshop
spec:
  ports:
  - port: 80
    name: web
  selector:
    purpose: statefulset 
    project: roboshop    
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset
spec:
  selector:
    matchLabels:
      purpose: statefulset 
      project: roboshop    # has to match .spec.template.metadata.labels
  serviceName: "headless-svc"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        purpose: statefulset 
        project: roboshop # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: pvc
          mountPath: /usr/share/nginx/html
  # This is nothing but PVC, but you can directly create here        
  volumeClaimTemplates:
  - metadata:
      name: pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 2Gi    

